version: "3.8"

services:
  postgres:
    image: "postgres:latest"
    container_name: my-postgres-container
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - ./data:/var/lib/postgresql/data
    networks:
      - my-network
  test-db:
    image: "postgres:latest"
    environment:
      POSTGRES_USER: testuser
      POSTGRES_PASSWORD: password
      POSTGRES_DB: aqdb-test
    ports:
      - "5436:5432"
    volumes:
      - ./test-data:/var/lib/postgresql/data
    networks:
      - my-network
      
networks:
  my-network: